"""unique repo id

Revision ID: 2800373af2c1
Revises: b0dcc4393940
Create Date: 2024-09-19 19:35:53.816791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2800373af2c1"
down_revision: Union[str, None] = "b0dcc4393940"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "repositories", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repositories", type_="unique")
    # ### end Alembic commands ###
