"""add bytes to languages

Revision ID: 41e68099b606
Revises: 2800373af2c1
Create Date: 2024-09-19 20:51:31.309936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e68099b606'
down_revision: Union[str, None] = '2800373af2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('num_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'num_bytes')
    # ### end Alembic commands ###
