"""empty message

Revision ID: 9704edd639f8
Revises: 0db22f842cf9
Create Date: 2024-10-11 17:54:43.073970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9704edd639f8'
down_revision: Union[str, None] = '0db22f842cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('cluster', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'cluster')
    # ### end Alembic commands ###
