"""make more nullable

Revision ID: 9ab5262fd5f1
Revises: 80192dc7386d
Create Date: 2024-09-19 22:57:49.824520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ab5262fd5f1"
down_revision: Union[str, None] = "80192dc7386d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("organizations", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "organizations", "repos_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "events_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "hooks_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "issues_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "members_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "public_members_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "avatar_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "organizations", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("organizations", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "organizations", "is_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "organizations",
        "has_organization_projects",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "organizations",
        "has_repository_projects",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "organizations", "html_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "node_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "avatar_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "followers_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "following_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "gists_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "starred_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "subscriptions_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "organizations_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "repos_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "events_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "received_events_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "type_of", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "site_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "hireable", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("users", "hireable", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "site_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "type_of", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "received_events_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "events_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "repos_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "organizations_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "subscriptions_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "starred_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "gists_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "following_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "followers_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "avatar_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "node_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "organizations", "html_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations",
        "has_repository_projects",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "organizations",
        "has_organization_projects",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "organizations", "is_verified", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("organizations", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "organizations", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations", "avatar_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations",
        "public_members_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "organizations", "members_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations", "issues_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations", "hooks_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations", "events_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "organizations", "repos_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("organizations", "url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
